service: cvs-svc-defect
# from 3.0 warnings will be thrown as errors
configValidationMode: warn
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-typescript

provider:
  profile: ${env:AWS_PROVIDER_PROFILE, 'default'}
  name: aws
  region: ${env:AWS_REGION, 'local'}
  runtime: nodejs16.x
  stage: ${env:NODE_ENV, 'local'}
  # To load environment variables externally
  # copy ./.env.example to ./.env.local.
  environment:
    SERVICE_VERSION: ${env:API_VERSION}
    AWS_REGION: ${self:provider.region}
    AWS_STAGE: ${self:provider.stage}
    SERVICE: ${self:service}

  tracing:
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  getDefects:
    handler: src/handler.handler
    events:
      - http:
          path: defects
          method: get

custom:
  serverless-offline:
    httpPort: ${env:AWS_SERVER_PORT, 3001}
  dynamodb:
    stages:
      - dev
      - test
      - local
    start:
      port: 8001
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      defects:
        sources:
          - table: cvs-local-defects
            sources: [./tests/resources/defects.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-defects
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
