service: cvs-svc-defect

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  getDefects:
    handler: src/handler.getDefects
    events:
    - http:
        path: defects
        method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMO_TABLE}
        AttributeDefinitions:
        - AttributeName: imNumber
          AttributeType: N
        KeySchema:
        - AttributeName: imNumber
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  serverless-offline:
    port: ${env:SERVERLESS_PORT}
  dynamodb:
    start:
      port: ${env:DYNAMO_PORT}
      inMemory: true
      migrate: true
      seed: true
    seed:
      defects:
        sources:
        - table: ${env:DYNAMO_TABLE}
          sources: [./offline/migrations/defects.json]
