service: cvs-svc-defect

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  tracing:
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  getDefects:
    handler: src/handler.handler
    events:
      - http:
          path: "defects"
          method: get

custom:
  serverless-offline:
    port: 3001
  dynamodb:
    stages:
      - dev
      - test
    start:
      port: 8001
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      defects:
        sources:
          - table: cvs-local-defects
            sources: [./tests/resources/defects.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-defects
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-tracing
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
