service: cvs-svc-defect

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  getDefects:
    handler: src/handler.getDefects
    events:
    - http:
        path: defects
        method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-${env:ENV}-dft-defects
        AttributeDefinitions:
        - AttributeName: imNumber
          AttributeType: N
        KeySchema:
        - AttributeName: imNumber
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  serverless-offline:
    port: 3000
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false
    seed:
      defects:
        sources:
        - table: cvs-${env:ENV}-dft-defects
          sources: [./tests/resources/defects.json]
