functions:
  - getDefects:
      method: GET
      path: /defects
      proxy: null
      function: getDefects
      event: apigateway
  - getIvaDefectsByManual:
      method: GET
      path: /defects/iva/manual/{+proxy}
      proxy: :id
      function: getIvaDefectsByManual
      event: apigateway
  - getIvaDefects:
      method: GET
      path: /defects/iva
      proxy: null
      function: getIvaDefects
      event: apigateway

invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://127.0.0.1:3001
    functions:
      getDefects:
        name: cvs-svc-defects
        mock: tests/resources/defects.json
      getIvaDefectsByManual:
        name: cvs-svc-defects
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      getDefects:
        name: defects-${BRANCH}
dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://127.0.0.1:8003
    table: cvs-local-defects
    keys:
      - defects
  local-global:
    params:
      region: localhost
      endpoint: http://127.0.0.1:8000
    table: cvs-local-global-defects
  remote:
    params: {}
    table: cvs-${BRANCH}-defects
serverless:
  basePath: /${BRANCH}
  port: 3001
