functions:
  - getDefects:
      method: GET
      path: /defects
      proxy: null
      function: getDefects
      event: apigateway

invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://localhost:3000
    functions:
      getDefects:
          name: cvs-svc-defects
          mock: tests/resources/defects.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      getDefects:
          name: defects-${BRANCH}
dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://localhost:8001
    table: cvs-local-defects
    keys:
      - defects
  local-global:
    params:
      region: localhost
      endpoint: http://localhost:8000
    table: cvs-local-global-defects
  remote:
    params: {}
    table: cvs-${BRANCH}-defects
serverless:
  basePath: /${BRANCH}
  port: 3001
