functions:
  - getDefects:
      method: GET
      path: /defects
      proxy: null
      function: getDefects
      event: apigateway
  - getRequiredStandards:
      method: GET
      path: /defects/requiredstandards
      proxy: null
      function: getRequiredStandards
      event: apigateway

invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://127.0.0.1:3001
    functions:
      getDefects:
        name: cvs-svc-defects
        mock: tests/resources/defects.json
      getRequiredStandards:
        name: cvs-svc-iva-defects
        mock: tests/resources/iva-defects.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      getDefects:
        name: defects-${BRANCH}
dynamodb:
  local:
    defects:
      region: localhost
      endpoint: http://127.0.0.1:8003
      table: cvs-local-defects
    ivaDefects:
      region: localhost
      endpoint: http://127.0.0.1:8003
      table: cvs-local-iva-defects
    keys:
      - Defects
      - IVA defects
  local-global:
    defects:
      region: localhost
      endpoint: http://127.0.0.1:8000
      table: cvs-local-global-defects
    ivaDefects:
      region: localhost
      endpoint: http://127.0.0.1:8000
      table: cvs-local-global-iva-defects
    keys:
      - Defects
      - IVA defects
  remote:
    defects:
      table: cvs-${BRANCH}-defects
    ivaDefects:
      table: cvs-${BRANCH}-iva-defects
serverless:
  basePath: /${BRANCH}
  port: 3001
