name: OPENAPI-GEN

on:
  push:
    branches: ["develop", "feature/VTMDEV-1"]
  pull_request:
    branches: ["develop", "feature/VTMDEV-1"]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Generate Services
        run: |
          java -jar main/.github/workflows/openapi-generator-cli.jar generate \
          -i ./main/docs/defects-api.yml \
          -g typescript-angular \
          -o ./defects

      - uses: actions/checkout@v3
        with:
          repository: dvsa/cvs-app-vtm
          path: vtm

      - name: Debug
        run: ls
